// Mapping nom de plante → titre de page Wikipedia (EN) pour récupérer la photo
export const WIKI_TITLES = {
  'Tomate':          'Tomato',
  'Tomate cerise':   'Cherry_tomato',
  'Poivron':         'Bell_pepper',
  'Aubergine':       'Eggplant',
  'Courgette':       'Zucchini',
  'Concombre':       'Cucumber',
  'Potiron':         'Pumpkin',
  'Melon':           'Cantaloupe',
  'Haricot vert':    'Green_bean',
  'Pois':            'Pea',
  'Carotte':         'Carrot',
  'Radis':           'Radish',
  'Betterave':       'Beetroot',
  'Laitue':          'Lettuce',
  'Épinard':         'Spinach',
  'Mâche':           'Valerianella_locusta',
  'Roquette':        'Eruca_vesicaria',
  'Basilic':         'Basil',
  'Persil':          'Parsley',
  'Ciboulette':      'Allium_schoenoprasum',
  'Coriandre':       'Coriander',
  'Menthe':          'Mentha',
  'Thym':            'Thyme',
  'Romarin':         'Rosemary',
  'Fraise':          'Strawberry',
  'Capucine':        'Nasturtium',
  'Souci':           'Calendula',
  'Géranium':        'Pelargonium',
  'Pétunias':        'Petunia',
  'Lavande':         'Lavender',
  'Tournesol':       'Common_sunflower',
  'Cosmos':          'Cosmos_(plant)',
  "Œillet d'Inde":   'Tagetes',
  'Piment fort':     'Chili_pepper',
  'Physalis':        'Physalis_peruviana',
  'Gingembre':       'Ginger',
  'Citronnelle':     'Cymbopogon',
  'Tomatille':       'Tomatillo',
  'Patate douce':    'Sweet_potato',
  'Chlorophytum':    'Chlorophytum_comosum',
  'Carex':           'Carex',
  'Fusain':          'Euonymus',
  'Picea glauca':    'Picea_glauca',
  'Yucca':           'Yucca',
  'Orpin':           'Sedum',
};
